version: '3'
services:
  kafka-topics-ui:
    container_name: kafka-topics-ui
    build:
      context: ..
      dockerfile: Dockerfile
    image: parrotstream/kafka-topics-ui:latest
    external_links:
    - kafka
    ports:
    - 8001:8001
    environment:
      KAFKA_REST_PROXY_URL: http://kafka:8082
      PROXY: "true"
      PORT: 8001
networks:
  default:
    external:
      name: parrot_default
