version: '3'
services:
  kafka-topics-ui:
    build:
      context: ..
      dockerfile: Dockerfile
    image: parrotstream/kafka-topics-ui:0.9.2
    networks:
    - parrot
    ports:
    - 8000:8000
    environment:
      KAFKA_REST_PROXY_URL: http://kafka:8082
      PROXY: "true"
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge
